# Custom training arguments
teacher_name: "Qwen/Qwen2.5-1.5B-Instruct"
quantize_teacher: true
xlstm_config_path: "./xlstm_config.yaml"
dataset_url: "Salesforce/wikitext"
data_subset: "wikitext-103-v1"
train_samples: 5000

# CE-loss args
ce_weight: 0.2
final_ce_weight: 1
ce_schedule: "no-op"

# KL-loss args
kl_weight: 0.8
final_kl_weight: 1
kl_schedule: "increase"

# Temperature args
temperature: 2
final_temperature: 1
temperature_schedule: "decrease"

# HF TrainerArguments arguments
num_train_epochs: 1
gradient_accumulation_steps: 4
learning_rate: 0.0001
weight_decay: 1e-3
lr_scheduler_type: "cosine"
torch_compile: true

output_dir: "distil-xlstm-artifacts"
logging_dir: "distil-xlstm-logs"
report_to: "tensorboard"
logging_steps: 50
save_steps: 100
hub_private_repo: true

fp16: false
use_cpu: false
push_to_hub: true
resume_from_checkpoint: "distil-xlstm-artifacts"
hub_model_id: "thiomajid/distil-xlstm"
gradient_checkpointing: false
