# Custom training arguments
teacher_name: "Qwen/Qwen2.5-1.5B-Instruct"
quantize_teacher: true
xlstm_config_path: "./xlstm_config.yaml"
dataset_url: "HuggingFaceFW/fineweb"

train_subset: "default"
train_split: "train"
train_samples: 10000

eval_subset: "CC-MAIN-2018-43"
eval_split: "train"
eval_samples: 1000
features: ["text"]

# Loss terms weights
delta: 0.01

alpha: 0.5
final_alpha: 0.5
alpha_schedule: "no-op"

ce_weight: 0.4
final_ce_weight: 0.4
ce_schedule: "no-op"

kl_weight: 0.2
final_kl_weight: 0.2
kl_schedule: "no-op"

frobenius_weight: 0.4
final_frobenius_weight: 0.4
frobenius_schedule: "no-op"

# Temperature args
temperature: 2
final_temperature: 0.7
temperature_schedule: "no-op"

# HF TrainerArguments arguments
num_train_epochs: 10
gradient_accumulation_steps: 4
per_device_train_batch_size: 8
per_device_eval_batch_size: 8

learning_rate: 0.0002
# weight_decay: 0.001
warmup_ratio: 0.1
optim: "adamw_torch"
lr_scheduler_type: "cosine"
torch_compile: true
fp16: true
use_cpu: false
gradient_checkpointing: false

output_dir: "artifacts"
logging_dir: "artifacts"
report_to: "tensorboard"
logging_steps: 100
save_steps: 100
hub_private_repo: false
save_total_limit: 2
load_best_model_at_end: true
eval_strategy: "steps"

push_to_hub: true
resume_from_checkpoint: "artifacts"
hub_model_id: "thiomajid/raw-xlstm"
remove_unused_columns: false
