# Custom training arguments
teacher_name: "Qwen/Qwen2.5-1.5B-Instruct"
quantize_teacher: true
xlstm_config_path: "./xlstm_config.yaml"
dataset_url: "HuggingFaceFW/fineweb"

train_subset: "default"
train_split: "train"
train_samples: 10000

eval_subset: "CC-MAIN-2018-43"
eval_split: "train"
eval_samples: 1000
features: ["text"]

# CE-loss args
ce_weight: 0.2
final_ce_weight: 1
ce_schedule: "no-op"

# KL-loss args
kl_weight: 0.8
final_kl_weight: 1
kl_schedule: "increase"

# Temperature args
temperature: 0.7
final_temperature: 1
temperature_schedule: "decrease"

# HF TrainerArguments arguments
num_train_epochs: 2
gradient_accumulation_steps: 2
learning_rate: 0.0001
# weight_decay: 0.001
lr_scheduler_type: "cosine"
torch_compile: false
per_device_train_batch_size: 4
per_device_eval_batch_size: 4

output_dir: "artifacts"
logging_dir: "logs"
report_to: "tensorboard"
logging_steps: 100
save_steps: 100
hub_private_repo: false
save_total_limit: 2
load_best_model_at_end: true
eval_strategy: "steps"

fp16: true
use_cpu: false
push_to_hub: true
resume_from_checkpoint: "artifacts"
hub_model_id: "thiomajid/fineweb-distil-xlstm"
gradient_checkpointing: false
remove_unused_columns: false
