# Custom training arguments
teacher_name: "Qwen/Qwen2.5-1.5B-Instruct"
quantize_teacher: true
xlstm_config_path: "./xlstm_config.yaml"
dataset_url: "HuggingFaceFW/fineweb"

train_subset: "default"
train_split: "train"
train_samples: 10000

eval_subset: "CC-MAIN-2018-43"
eval_split: "train"
eval_samples: 1000
features: ["text"]

# Loss alpha weight
delta: 0.05
alpha: 0.8
final_alpha: 0.5
alpha_schedule: "decrease"

# Temperature args
temperature: 2
final_temperature: 1
temperature_schedule: "decrease"

# HF TrainerArguments arguments
num_train_epochs: 2
gradient_accumulation_steps: 4
learning_rate: 0.0002
# weight_decay: 0.001
warmup_ratio: 0.1
lr_scheduler_type: "cosine"
torch_compile: false
per_device_train_batch_size: 16
per_device_eval_batch_size: 16

output_dir: "artifacts"
logging_dir: "logs"
report_to: "tensorboard"
logging_steps: 100
save_steps: 100
hub_private_repo: false
save_total_limit: 2
load_best_model_at_end: true
eval_strategy: "steps"

fp16: true
use_cpu: false
push_to_hub: true
resume_from_checkpoint: "artifacts"
hub_model_id: "thiomajid/fineweb-distil-xlstm-v2"
gradient_checkpointing: false
remove_unused_columns: false
