vocab_size: 32_000
context_length: 512
num_blocks: 6
embedding_dim: 256
slstm_at: [0, 2, 4]

mlstm_block:
  mlstm:
    conv1d_kernel_size: 4
    qkv_proj_blocksize: 32
    num_heads: 16

slstm_block:
  slstm:
    backend: "cuda"
    num_heads: 16
    conv1d_kernel_size: 4
    bias_init: "powerlaw_blockdependent"

  feedforward:
    proj_factor: 1.7
    act_fn: "gelu"
