vocab_size: 32_000
context_length: 1024
num_blocks: 3
embedding_dim: 256
dropout: 0.2
slstm_at: [1]

mlstm_block:
  mlstm:
    conv1d_kernel_size: 4
    qkv_proj_blocksize: 16
    num_heads: 4

slstm_block:
  slstm:
    backend: "vanilla"
    num_heads: 4
    conv1d_kernel_size: 4
    bias_init: "powerlaw_blockdependent"

  feedforward:
    proj_factor: 1.7
    act_fn: "gelu"
