context_lenght: 1024
num_blocks: 12
embedding_dim: 512
# slstm_at: [1, 3, 5, 7, 9]

mlstm_block:
  mlstm:
    conv1d_kernel_size: 4
    qkv_proj_blocksize: 4
    num_heads: 4

slstm_block:
  sltm:
    backend: "vanilla"
    num_heads: 4
    conv1d_kernel_size: 4
    bias_init: "powerlaw_blockdependent"

  feedforward:
    proj_factor: 1.3
    act_fn: "gelu"
