vocab_size: 32_000
context_length: 512
num_blocks: 1
embedding_dim: 256
slstm_at: []

mlstm_block:
  mlstm:
    conv1d_kernel_size: 4
    qkv_proj_blocksize: 4
    num_heads: 4

slstm_block:
  slstm:
    backend: "vanilla"
    num_heads: 4
    conv1d_kernel_size: 4
    bias_init: "powerlaw_blockdependent"

  feedforward:
    proj_factor: 1.3
    act_fn: "gelu"
